### ISSUE TITLE
Mac examples exit with error code 255

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#162]
All examples have such OnClose event:

    OnClose():
        self.Destroy()
        cefpython.Shutdown()
        wx.GetApp().Exit()

I don't know any other way to exit wx app on mac. If Exit() call is removed 
then there is error: "Segmentation fault: 11".

Original issue reported on code.google.com by `czarek.t...@gmail.com` on 13 Jan 2015 at 2:20

**Comment by kollivier** [comment]
I just ran across this issue and I wanted to note that I was able to fix it by calling cefpython.ShutDown() before destroying the wx window, rather than after. I suspect what is happening is that in a single-window app, window.Destroy() also leads to the app's main loop being destroyed, which IIRC on Mac destroys the app's NSAutoreleasePool as well. Then when cefpython tries to pop the NSAutoreleasePool to trigger garbage collection, it crashes because the NSAutoreleasePool doesn't exist any longer.

**Comment by cztomczak** [comment]
@kollivier I tried your suggestion, but it doesn't work for me in CEF v56.0 when running the new wxpython.py example.

For reference, a similar issue was reported on CEF Forum here:
http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=13737

**Comment by cztomczak** [comment]
Fixed it with such code in OnClose in v56:
```
        if MAC:
            # On Mac things work differently, other steps are required
            self.browser.CloseBrowser()
            self.clear_browser_references()
            self.Destroy()
            global g_count_windows
            g_count_windows -= 1
            if g_count_windows == 0:
                cef.Shutdown()
                wx.GetApp().ExitMainLoop()
                # Call _exit otherwise app exits with code 255 (Issue #162).
                # noinspection PyProtectedMember
                os._exit(0)
```
