### ISSUE TITLE
Kivy example: hover not working, on_touch_move() not called when moving mouse

### ISSUE THREAD

**Issue by jegger** [cztomczak/cefpython#243]
There seems to be an odd behavior in the Kivy example regarding SendMouseMoveEvent / SendMouseClickEvent.

**Behavior cefclient**
When I navigate to http://jegger.ch/datapool/app/test_events.html in ./cefclient --off-screen-rendering-enabled I get (what I expect) light-red dots when hovering and "dark"-red dots when I move the mouse while pressing the left mouse-button.

**Behavior Kivy**
If I press down in kivy I see the arrows registering the mouse-down but the dots are light-red afterwards. They should be dark-red, shouldn't they? I can't see anything wrong in the logic of the kivy_.py example. It was working (dark-dots while pressing down and move) with the old CEF.

Any ideas?

**Comment by cztomczak** [comment]
Mouse events in cefclient for reference:
* Click - https://bitbucket.org/chromiumembedded/cef/src/60b37186508edb13da9dff185f1b9658be674152/tests/cefclient/browser/browser_window_osr_gtk.cc?at=master&fileviewer=file-view-default#browser_window_osr_gtk.cc-1279
* Move - https://bitbucket.org/chromiumembedded/cef/src/60b37186508edb13da9dff185f1b9658be674152/tests/cefclient/browser/browser_window_osr_gtk.cc?at=master&fileviewer=file-view-default#browser_window_osr_gtk.cc-1390
* Scroll - https://bitbucket.org/chromiumembedded/cef/src/60b37186508edb13da9dff185f1b9658be674152/tests/cefclient/browser/browser_window_osr_gtk.cc?at=master&fileviewer=file-view-default#browser_window_osr_gtk.cc-1425

**Comment by cztomczak** [comment]
on_touch_move() is not called by Kivy when moving my mouse. It is only being called after I click and hold down mouse button and then move. Hovering over links in Google doesn't underline them in kivy_.py when compared to cefclient.

I don't see how this can be related to old/new CEF - it is Kivy's function on_touch_move() not being called during mouse moves. Using Kivy 1.7.2.

**Comment by cztomczak** [comment]
Missing mouse move events that I described the issue I think needs to be resolved first. The second issue - of light-red dots when moving mouse while holding mouse button - I think is related to the first issue due to some mouse events missing.

Tested both cefpython 31.2 and 51.0 - in both cases it behaves the same.

**Comment by cztomczak** [comment]
Related issue in kivy/kivy: https://github.com/kivy/kivy/issues/325

Commit that is supposed to fix it updates WindowPygame.mouse_pos attribute on mouse motion. This can be access inside widget using self.get_root_window().mouse_pos.

The main issue of mouse move events fixed in commit 7b8d7e949eb280fa118f1862971c8338b85e77b9.

However this still doesn't fix light-red dots when moving mouse while holding mouse button.

**Comment by cztomczak** [comment]
Second issue of light-red dots fixed in commit 779e2d552c968a71841f7523d36f4a77b9e9ce48. Setting modifiers=EVENTFLAG_LEFT_MOUSE_BUTTON to SendMouseMoveEvent() in on_touch_down().

**Comment by jegger** [comment]
Hey thanks! The modifier was the missing piece :)

Just for clarification: I never meant that the "hover" state should be implemented (when I created this issue) in Kivy (as on touch applications there is no hover state by design - yet). However I think it is good you implemented it here for demonstration - even it does not work with all kivy window providers.

**Comment by cztomczak** [comment]
Fix mouse move events by checking whether the "mouse_pos" attribute is available in Root Window. Fix in commit 638507ad26df5953d1421a7b7ff29f56f957e887.
