### ISSUE TITLE
CefDictionaryValueToPyDict(): max nesting level (8) exceeded

### ISSUE THREAD

**Issue by PieceOfGood** [cztomczak/cefpython#545]
An endless stream of messages to the program console and StdERr about exceeding the level of nesting, although the program successfully executed.

The essence of the problem is fully described [in this](https://groups.google.com/forum/#!topic/cefpython/9PiDFPQ37p8) discussion.

**Comment by cztomczak** [comment]
In the meantime to fix it yourself edit these files:
1. File [src/process_message_utils.pyx](https://github.com/cztomczak/cefpython/blob/e72609c2874e38bc58ba54bd114861bf32dab8ce/src/process_message_utils.pyx). In a few places there is code such as this `if nestingLevel > 8:`. Modify it to return from a function silently instead of raising Python exception.
2. Remove lines 116-117 that log error message in [src/subprocess/v8utils.cpp](https://github.com/cztomczak/cefpython/blob/e72609c2874e38bc58ba54bd114861bf32dab8ce/src/subprocess/v8utils.cpp#L116).

And rebuild the cefpython module. Build instructions can be found in the docs/ directory.

**Comment by PieceOfGood** [comment]
I get an exception as a result of the build:
```
...
[cython_setup.py] Detect Windows SDK library directory
Traceback (most recent call last):
  File "G:\pyProj\_BuildCEF\cefpython\tools/cython_setup.py", line 453, in <module>
    main()
  File "G:\pyProj\_BuildCEF\cefpython\tools/cython_setup.py", line 111, in main
    options["library_dirs"] = get_library_dirs()
  File "G:\pyProj\_BuildCEF\cefpython\tools/cython_setup.py", line 347, in get_library_dirs
    get_winsdk_lib(),
  File "G:\pyProj\_BuildCEF\cefpython\tools/cython_setup.py", line 150, in get_winsdk_lib
    % ret)
Exception: Windows SDK Lib directory not found: C:\\Program Files\\Microsoft SDKs\\Windows\\v7.1\\Lib\\x64

[build.py] Cleanup: remove pyx files in build_cefpython/
[build.py] ERROR: failed to build the cefpython module
```
I have windows 10 and here is mentioned SDK for windows 7

**Comment by cztomczak** [comment]
I've edited my previous comment with another solution to fix the issue in app js code. I think it's best to do it that way. Reporter's issue was fixed, so closing.
